language: node_js
node_js: "10"
before_install:
  - export DISPLAY=:99.0
  - npm i -g npm@latest
  - npm i -g codecov
cache: npm
install:
  - npm install
script:
  - npm run lint
  - npm run test
  - npm run build
  - python node_modules/travis-weigh-in/weigh_in.py dist/renew.js
  - codecov
